version: '3.8'

services:
  loan-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_KEY=loan-service-secret-key-2024
      - DATABASE_URL=/app/data/database.sqlite
      - PORT=3000
      - CORS_ORIGIN=*
    volumes:
      # Mount a volume for persistent database storage
      - loan_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  loan_data:
    driver: local